site_name: ACCORD Project Documentation
theme: windmill
markdown_extensions:
  - attr_list
extra:
  logo: accord.jpg
  article_nav_top: false
  article_nav_bottom: false
nav:
  - Home: index.md
  - Rule Formalisation:
    - ACCORD Building Compliance Ontology: aec3po.md
    - Rule Formalisation Process and BCRL Format: process.md
    - Natural Langauge Processing of Building Codes: nlp.md
    - ACCORD Rule Formalisation Tool: rft.md
    - Semantic Storage: graphdb.md
  - ACCORD Cloud Architecture: cloud.md
  - ACCORD Core Components:
    - Rule Formalization Tool: rft.md
    - Data Dictionary Repository: dd.md
    - Building Codes and Rules Repository: rr.md
    - IDS Repository: idsr.md
    - IDS Generation Tool: idsgen.md
    - Model and Data Requirement Validation: validation.md
    - Process Execution: execution.md
    - Data Storage: datastorage.md
    - Orchestrating Microservices: orchestration.md
  - ACCORD APIs: apis.md
  - ACCORD Integration Strategies: strategies.md
  - Extensibility of ACCORD Cloud Architecture: extensibility.md
  - Compliance Checking Microservices:
    - Urban Parameter Regulations Checking: urban.md
    - Solibri and Cloudpermit: solibri.md
    - AC(CO2)RD whole life carbon assessment: flca.md
    - Future Insight Clearly.BIM: clearly.md
    - Eurocode Verification: eurocode.md
    - Planned Land Use Checker: landuse.md
    - Environmental Compliance: glca.md
    - Timber Construction Compliance Checker: timber.md

